"""Build the Assignment 5 Part 2 submission document.

The calculations and figures are generated by analysis.R. This
script reads those verified outputs and packages the required code, tables,
plots, and written interpretation into the final DOCX.

Usage:
    Rscript assignment_5/part_2/analysis.R
    uv run python assignment_5/part_2/build_submission.py
"""

from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path

from docx import Document
from docx.enum.section import WD_SECTION
from docx.enum.table import WD_CELL_VERTICAL_ALIGNMENT, WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH, WD_BREAK, WD_LINE_SPACING
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor


PART_ROOT = Path(__file__).resolve().parent
REPO_ROOT = PART_ROOT.parent.parent
FIGURE_DIR = PART_ROOT / "figures"
TABLE_DIR = PART_ROOT / "tables"
OUTPUT_PATH = PART_ROOT / "docs" / "submissions" / "26120004_Team2_Assignment5_Part2.docx"

REGISTRATION_NUMBER = "26120004"
TEAM_NUMBER = "2"
PROJECT_TITLE = "Historical Stock Analysis"
DATASET_SOURCE = (
    "data/stock_data.csv - "
    "https://www.kaggle.com/datasets/ibrahimshahrukh/top-50-companies-dataset "
    "(the source page has since been removed by its uploader)"
)
TEAM_MEMBERS = (
    "Karthikeyan M (26120004), Mirthula M (26120121), "
    "Lakshmi Mayuri Kavya N (26120161)"
)
SUBMISSION_DATE = "19 August 2026"

# Plain academic layout, kept close to the assignment sheet.
PAGE_WIDTH = Inches(8.5)
PAGE_HEIGHT = Inches(11)
PAGE_MARGIN = Inches(1)
HEADER_DISTANCE = Inches(0.492)
FOOTER_DISTANCE = Inches(0.492)
CONTENT_WIDTH_DXA = 9360
TABLE_INDENT_DXA = 120
CELL_MARGINS_DXA = {"top": 80, "bottom": 80, "start": 120, "end": 120}

FONT_BODY = "Times New Roman"
FONT_CODE = "Courier New"
COLOR_NAVY = "000000"
COLOR_BLUE = "000000"
COLOR_DARK_BLUE = "000000"
COLOR_TABLE_BLUE = "0B2545"
COLOR_MUTED = "595959"
COLOR_LIGHT_GRAY = "F2F4F7"
COLOR_BORDER = "C9D1D9"
COLOR_CODE_FILL = "F6F8FA"
COLOR_WHITE = "FFFFFF"


def set_cell_shading(cell, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = tc_pr.find(qn("w:shd"))
    if shd is None:
        shd = OxmlElement("w:shd")
        tc_pr.append(shd)
    shd.set(qn("w:fill"), fill)


def set_cell_margins(cell) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_mar = tc_pr.find(qn("w:tcMar"))
    if tc_mar is None:
        tc_mar = OxmlElement("w:tcMar")
        tc_pr.append(tc_mar)
    for side, value in CELL_MARGINS_DXA.items():
        node = tc_mar.find(qn(f"w:{side}"))
        if node is None:
            node = OxmlElement(f"w:{side}")
            tc_mar.append(node)
        node.set(qn("w:w"), str(value))
        node.set(qn("w:type"), "dxa")


def set_repeat_table_header(row) -> None:
    tr_pr = row._tr.get_or_add_trPr()
    tbl_header = OxmlElement("w:tblHeader")
    tbl_header.set(qn("w:val"), "true")
    tr_pr.append(tbl_header)


def set_table_geometry(table, widths_dxa: list[int]) -> None:
    assert sum(widths_dxa) == CONTENT_WIDTH_DXA
    table.alignment = WD_TABLE_ALIGNMENT.LEFT
    table.autofit = False

    tbl_pr = table._tbl.tblPr
    for tag in ("w:tblW", "w:tblInd", "w:tblLayout"):
        old = tbl_pr.find(qn(tag))
        if old is not None:
            tbl_pr.remove(old)

    tbl_w = OxmlElement("w:tblW")
    tbl_w.set(qn("w:w"), str(CONTENT_WIDTH_DXA))
    tbl_w.set(qn("w:type"), "dxa")
    tbl_pr.append(tbl_w)

    tbl_ind = OxmlElement("w:tblInd")
    tbl_ind.set(qn("w:w"), str(TABLE_INDENT_DXA))
    tbl_ind.set(qn("w:type"), "dxa")
    tbl_pr.append(tbl_ind)

    tbl_layout = OxmlElement("w:tblLayout")
    tbl_layout.set(qn("w:type"), "fixed")
    tbl_pr.append(tbl_layout)

    grid = table._tbl.tblGrid
    for child in list(grid):
        grid.remove(child)
    for width in widths_dxa:
        grid_col = OxmlElement("w:gridCol")
        grid_col.set(qn("w:w"), str(width))
        grid.append(grid_col)

    for row in table.rows:
        for index, cell in enumerate(row.cells):
            tc_pr = cell._tc.get_or_add_tcPr()
            tc_w = tc_pr.find(qn("w:tcW"))
            if tc_w is None:
                tc_w = OxmlElement("w:tcW")
                tc_pr.append(tc_w)
            tc_w.set(qn("w:w"), str(widths_dxa[index]))
            tc_w.set(qn("w:type"), "dxa")
            set_cell_margins(cell)
            cell.vertical_alignment = WD_CELL_VERTICAL_ALIGNMENT.CENTER


def set_table_borders(table, color: str = COLOR_BORDER, size: int = 4) -> None:
    tbl_pr = table._tbl.tblPr
    borders = tbl_pr.find(qn("w:tblBorders"))
    if borders is None:
        borders = OxmlElement("w:tblBorders")
        tbl_pr.append(borders)
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        element = borders.find(qn(f"w:{edge}"))
        if element is None:
            element = OxmlElement(f"w:{edge}")
            borders.append(element)
        element.set(qn("w:val"), "single")
        element.set(qn("w:sz"), str(size))
        element.set(qn("w:space"), "0")
        element.set(qn("w:color"), color)


def set_run_font(
    run,
    *,
    name: str = FONT_BODY,
    size: float | None = None,
    color: str | None = None,
    bold: bool | None = None,
    italic: bool | None = None,
) -> None:
    run.font.name = name
    run._element.get_or_add_rPr().get_or_add_rFonts().set(qn("w:ascii"), name)
    run._element.get_or_add_rPr().get_or_add_rFonts().set(qn("w:hAnsi"), name)
    if size is not None:
        run.font.size = Pt(size)
    if color is not None:
        run.font.color.rgb = RGBColor.from_string(color)
    if bold is not None:
        run.bold = bold
    if italic is not None:
        run.italic = italic


def configure_styles(doc: Document) -> None:
    styles = doc.styles

    normal = styles["Normal"]
    normal.font.name = FONT_BODY
    normal.font.size = Pt(11)
    normal.font.color.rgb = RGBColor(0, 0, 0)
    normal._element.rPr.rFonts.set(qn("w:ascii"), FONT_BODY)
    normal._element.rPr.rFonts.set(qn("w:hAnsi"), FONT_BODY)
    normal.paragraph_format.space_before = Pt(0)
    normal.paragraph_format.space_after = Pt(6)
    normal.paragraph_format.line_spacing = 1.10

    heading_tokens = {
        "Heading 1": (15, COLOR_BLUE, 14, 6),
        "Heading 2": (12, COLOR_BLUE, 10, 4),
        "Heading 3": (11, COLOR_DARK_BLUE, 8, 4),
    }
    for style_name, (size, color, before, after) in heading_tokens.items():
        style = styles[style_name]
        style.font.name = FONT_BODY
        style.font.size = Pt(size)
        style.font.bold = True
        style.font.color.rgb = RGBColor.from_string(color)
        style._element.rPr.rFonts.set(qn("w:ascii"), FONT_BODY)
        style._element.rPr.rFonts.set(qn("w:hAnsi"), FONT_BODY)
        style.paragraph_format.space_before = Pt(before)
        style.paragraph_format.space_after = Pt(after)
        style.paragraph_format.line_spacing = 1.10
        style.paragraph_format.keep_with_next = True
        style.paragraph_format.keep_together = True

    caption = styles["Caption"]
    caption.font.name = FONT_BODY
    caption.font.size = Pt(9)
    caption.font.italic = False
    caption.font.color.rgb = RGBColor.from_string(COLOR_MUTED)
    caption._element.rPr.rFonts.set(qn("w:ascii"), FONT_BODY)
    caption._element.rPr.rFonts.set(qn("w:hAnsi"), FONT_BODY)
    caption.paragraph_format.space_before = Pt(4)
    caption.paragraph_format.space_after = Pt(4)
    caption.paragraph_format.keep_with_next = True


def configure_section(section) -> None:
    section.page_width = PAGE_WIDTH
    section.page_height = PAGE_HEIGHT
    section.top_margin = PAGE_MARGIN
    section.right_margin = PAGE_MARGIN
    section.bottom_margin = PAGE_MARGIN
    section.left_margin = PAGE_MARGIN
    section.header_distance = HEADER_DISTANCE
    section.footer_distance = FOOTER_DISTANCE


def add_page_field(paragraph) -> None:
    run = paragraph.add_run()
    fld_char_begin = OxmlElement("w:fldChar")
    fld_char_begin.set(qn("w:fldCharType"), "begin")
    run._r.append(fld_char_begin)

    instruction_run = paragraph.add_run()
    instr_text = OxmlElement("w:instrText")
    instr_text.set(qn("xml:space"), "preserve")
    instr_text.text = " PAGE "
    instruction_run._r.append(instr_text)

    separator_run = paragraph.add_run()
    fld_char_separate = OxmlElement("w:fldChar")
    fld_char_separate.set(qn("w:fldCharType"), "separate")
    separator_run._r.append(fld_char_separate)

    result_run = paragraph.add_run("1")
    set_run_font(result_run, size=9, color=COLOR_MUTED)

    end_run = paragraph.add_run()
    fld_char_end = OxmlElement("w:fldChar")
    fld_char_end.set(qn("w:fldCharType"), "end")
    end_run._r.append(fld_char_end)


def configure_header_footer(section) -> None:
    header = section.header
    header_p = header.paragraphs[0]
    header_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    header_p.paragraph_format.space_after = Pt(0)

    footer = section.footer
    footer_p = footer.paragraphs[0]
    footer_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    footer_p.paragraph_format.space_before = Pt(0)
    footer_p.paragraph_format.space_after = Pt(0)
    run = footer_p.add_run("Team 2  |  Page ")
    set_run_font(run, size=9, color=COLOR_MUTED)
    add_page_field(footer_p)


def add_title_block(doc: Document) -> None:
    kicker = doc.add_paragraph()
    kicker.paragraph_format.space_before = Pt(5)
    kicker.paragraph_format.space_after = Pt(3)
    run = kicker.add_run("Assignment 5 - Part 2")
    set_run_font(run, size=14, color=COLOR_BLUE, bold=True)

    title = doc.add_paragraph()
    title.paragraph_format.space_before = Pt(0)
    title.paragraph_format.space_after = Pt(4)
    run = title.add_run("Data Wrangling with R")
    set_run_font(run, size=18, color=COLOR_NAVY, bold=True)
    title.paragraph_format.space_after = Pt(12)

    rows = [
        ("Team Number", TEAM_NUMBER),
        ("Project Title", PROJECT_TITLE),
        ("Dataset", DATASET_SOURCE),
        ("Team Members", TEAM_MEMBERS),
        ("Date", SUBMISSION_DATE),
    ]
    table = doc.add_table(rows=len(rows), cols=2)
    set_table_geometry(table, [2700, 6660])
    set_table_borders(table)
    for i, (label, value) in enumerate(rows):
        left, right = table.rows[i].cells
        set_cell_shading(left, COLOR_LIGHT_GRAY)
        p_left = left.paragraphs[0]
        p_left.paragraph_format.space_after = Pt(0)
        set_run_font(p_left.add_run(label), size=9.5, color=COLOR_TABLE_BLUE, bold=True)
        p_right = right.paragraphs[0]
        p_right.paragraph_format.space_after = Pt(0)
        set_run_font(p_right.add_run(value), size=9.5)

    intro = doc.add_paragraph()
    intro.paragraph_format.space_before = Pt(12)
    intro.paragraph_format.space_after = Pt(6)
    intro.add_run(
        "This is the same stock dataset we used in Assignment 4, with 230,111 rows. "
        "For this part, we used tidyr to switch between wide and long data, lubridate "
        "to work with the Date column, and dplyr and data.table to calculate the same "
        "grouped summary in two ways. Since the stocks trade in different currencies, "
        "we compare indexed prices or returns instead of comparing raw prices directly."
    )

def add_heading(doc: Document, text: str, level: int = 1) -> None:
    heading = doc.add_paragraph(style=f"Heading {level}")
    heading.add_run(text)


def shade_paragraph(paragraph, fill: str) -> None:
    p_pr = paragraph._p.get_or_add_pPr()
    shd = p_pr.find(qn("w:shd"))
    if shd is None:
        shd = OxmlElement("w:shd")
        p_pr.append(shd)
    shd.set(qn("w:fill"), fill)


def add_code_block(doc: Document, code: str) -> None:
    paragraph = doc.add_paragraph()
    paragraph.paragraph_format.left_indent = Inches(0.08)
    paragraph.paragraph_format.right_indent = Inches(0.08)
    paragraph.paragraph_format.space_before = Pt(4)
    paragraph.paragraph_format.space_after = Pt(8)
    paragraph.paragraph_format.line_spacing = 1.0
    paragraph.paragraph_format.keep_together = True
    shade_paragraph(paragraph, COLOR_CODE_FILL)
    lines = code.strip("\n").splitlines()
    for index, line in enumerate(lines):
        run = paragraph.add_run(line)
        set_run_font(run, name=FONT_CODE, size=8.2, color="24292F")
        if index < len(lines) - 1:
            run.add_break()


def add_code_comparison(doc: Document, left_code: str, right_code: str) -> None:
    table = doc.add_table(rows=2, cols=2)
    set_table_geometry(table, [4680, 4680])
    set_table_borders(table)
    headers = ("dplyr", "data.table")
    for index, label in enumerate(headers):
        cell = table.rows[0].cells[index]
        set_cell_shading(cell, COLOR_LIGHT_GRAY)
        p = cell.paragraphs[0]
        p.paragraph_format.space_after = Pt(0)
        set_run_font(p.add_run(label), size=10, color=COLOR_NAVY, bold=True)
    for index, code in enumerate((left_code, right_code)):
        cell = table.rows[1].cells[index]
        set_cell_shading(cell, COLOR_CODE_FILL)
        p = cell.paragraphs[0]
        p.paragraph_format.space_after = Pt(0)
        p.paragraph_format.line_spacing = 1.0
        for line_number, line in enumerate(code.strip().splitlines()):
            run = p.add_run(line)
            set_run_font(run, name=FONT_CODE, size=7.6, color="24292F")
            if line_number < len(code.strip().splitlines()) - 1:
                run.add_break()


def read_csv_rows(filename: str) -> list[dict[str, str]]:
    with (TABLE_DIR / filename).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def add_table_caption(doc: Document, text: str) -> None:
    caption = doc.add_paragraph(style="Caption")
    caption.add_run(text)


def add_data_table(
    doc: Document,
    headers: list[str],
    rows: list[list[str]],
    widths_dxa: list[int],
    alignments: list[int] | None = None,
) -> None:
    table = doc.add_table(rows=1, cols=len(headers))
    set_table_geometry(table, widths_dxa)
    set_table_borders(table)
    header_row = table.rows[0]
    set_repeat_table_header(header_row)
    for i, header in enumerate(headers):
        cell = header_row.cells[i]
        set_cell_shading(cell, COLOR_LIGHT_GRAY)
        p = cell.paragraphs[0]
        p.alignment = alignments[i] if alignments else WD_ALIGN_PARAGRAPH.LEFT
        p.paragraph_format.space_after = Pt(0)
        set_run_font(p.add_run(header), size=9, color=COLOR_NAVY, bold=True)

    for row_values in rows:
        cells = table.add_row().cells
        for i, value in enumerate(row_values):
            p = cells[i].paragraphs[0]
            p.alignment = alignments[i] if alignments else WD_ALIGN_PARAGRAPH.LEFT
            p.paragraph_format.space_after = Pt(0)
            set_run_font(p.add_run(value), size=8.8)
    set_table_geometry(table, widths_dxa)


def add_figure(doc: Document, filename: str, caption: str) -> None:
    add_table_caption(doc, caption)
    picture = doc.add_paragraph()
    picture.alignment = WD_ALIGN_PARAGRAPH.CENTER
    picture.paragraph_format.space_after = Pt(6)
    run = picture.add_run()
    run.add_picture(str(FIGURE_DIR / filename), width=Inches(5.8))


def add_b1(doc: Document) -> None:
    doc.add_page_break()
    add_heading(doc, "B.1 Reshape your data", 1)
    doc.add_paragraph(
        "We used AAPL, MSFT, NVDA, and AVGO for 2025 and kept the last trading day in "
        "each month. We then indexed every stock to 100 in January. All four stocks "
        "are listed in the US, and indexing them makes the change over time comparable "
        "even though their starting prices are different."
    )

    add_heading(doc, "Wide and long forms", 2)
    wide = read_csv_rows("b1_wide.csv")[:4]
    wide_rows = [
        [
            datetime.strptime(row["Month"], "%Y-%m-%d").strftime("%b %Y"),
            f'{float(row["AAPL"]):.1f}',
            f'{float(row["AVGO"]):.1f}',
            f'{float(row["MSFT"]):.1f}',
            f'{float(row["NVDA"]):.1f}',
        ]
        for row in wide
    ]
    add_table_caption(doc, "Table 1. Wide form (first four months; January 2025 = 100)")
    add_data_table(
        doc,
        ["Month", "AAPL", "AVGO", "MSFT", "NVDA"],
        wide_rows,
        [1800, 1890, 1890, 1890, 1890],
        [WD_ALIGN_PARAGRAPH.LEFT] + [WD_ALIGN_PARAGRAPH.CENTER] * 4,
    )

    long_rows_source = read_csv_rows("b1_long.csv")[:8]
    long_rows = [
        [
            datetime.strptime(row["Month"], "%Y-%m-%d").strftime("%b %Y"),
            row["Ticker"],
            f'{float(row["Indexed.Price"]):.1f}',
        ]
        for row in long_rows_source
    ]
    add_table_caption(doc, "Table 2. Long form (first eight rows)")
    add_data_table(
        doc,
        ["Month", "Ticker", "Indexed Price"],
        long_rows,
        [2800, 2300, 4260],
        [WD_ALIGN_PARAGRAPH.LEFT, WD_ALIGN_PARAGRAPH.CENTER, WD_ALIGN_PARAGRAPH.CENTER],
    )

    add_code_block(
        doc,
        """monthly_wide <- monthly_long_source %>%
  pivot_wider(names_from = Ticker, values_from = Indexed.Price)

monthly_long <- monthly_wide %>%
  pivot_longer(cols = all_of(selected_tickers),
               names_to = "Ticker", values_to = "Indexed.Price")""",
    )

    add_figure(
        doc,
        "b1_reshape_indexed_prices.png",
        "Figure 1. Monthly adjusted prices in 2025, indexed to 100 in January.",
    )
    doc.add_paragraph(
        "The long form was easier to plot. ggplot2 could use the Ticker column for the "
        "line colour and draw all four stocks with one geom_line() layer. In the wide "
        "form, every ticker is a separate column, which is useful for reading the table "
        "but less convenient for this chart. Figure 1 also shows the difference clearly: "
        "AVGO and NVDA finished 2025 near 158 and 155, while AAPL and MSFT finished near "
        "116 and 117."
    )


def add_b2(doc: Document) -> None:
    doc.add_page_break()
    add_heading(doc, "B.2 Parse and use a date/time field", 1)
    doc.add_paragraph(
        "The Date column came into R as plain text, which was the same issue we saw in "
        "Assignment 4. We converted it with ymd(), pulled out the year, month, and "
        "weekday, and used floor_date() to put the daily rows into monthly groups."
    )
    parsed = read_csv_rows("b2_parsed_date_sample.csv")[:3]
    parsed_rows = [
        [row["Date"], row["Ticker"], row["Year"], row["Month"], row["Weekday"]]
        for row in parsed
    ]
    add_table_caption(doc, "Table 3. Parsed date fields (sample)")
    add_data_table(
        doc,
        ["Date", "Ticker", "Year", "Month", "Weekday"],
        parsed_rows,
        [1900, 1800, 1200, 2100, 2360],
        [
            WD_ALIGN_PARAGRAPH.LEFT,
            WD_ALIGN_PARAGRAPH.LEFT,
            WD_ALIGN_PARAGRAPH.CENTER,
            WD_ALIGN_PARAGRAPH.LEFT,
            WD_ALIGN_PARAGRAPH.LEFT,
        ],
    )

    top_months = read_csv_rows("b2_top_volatility_months.csv")
    top_rows = [
        [
            datetime.strptime(row["Month"], "%Y-%m-%d").strftime("%B %Y"),
            f'{float(row["Mean.Abs.Return"]) * 100:.2f}%',
            row["Tickers"],
        ]
        for row in top_months
    ]
    add_table_caption(doc, "Table 4. Five months with the highest mean absolute daily return")
    add_data_table(
        doc,
        ["Month", "Mean Absolute Return", "Tickers"],
        top_rows,
        [3300, 3400, 2660],
        [WD_ALIGN_PARAGRAPH.LEFT, WD_ALIGN_PARAGRAPH.CENTER, WD_ALIGN_PARAGRAPH.CENTER],
    )

    add_code_block(
        doc,
        """stocks <- stocks %>%
  mutate(Date = lubridate::ymd(Date),
         Year = lubridate::year(Date),
         Month.Name = lubridate::month(Date, label = TRUE),
         Weekday = lubridate::wday(Date, label = TRUE),
         Month = lubridate::floor_date(Date, "month"))

monthly_volatility <- stocks %>%
  filter(!is.na(Daily.Return)) %>%
  group_by(Ticker, Month) %>%
  summarise(Mean.Abs.Return = mean(abs(Daily.Return)), .groups = "drop") %>%
  group_by(Month) %>%
  summarise(Mean.Abs.Return = mean(Mean.Abs.Return),
            Tickers = n(), .groups = "drop")""",
    )

    add_figure(
        doc,
        "b2_monthly_absolute_return.png",
        "Figure 2. Average absolute daily return by month, equal-weighted across available tickers.",
    )
    doc.add_paragraph(
        "Grouping the dates by month makes the high-volatility periods much easier to "
        "see. October 2008 is the highest month at 4.82%, followed by March 2020 at "
        "4.67% and November 2008 at 4.38%. We first calculated the average inside each "
        "ticker-month and then averaged across tickers. This stops a market with more "
        "companies in the dataset from receiving extra weight automatically."
    )


def add_b3(doc: Document) -> None:
    doc.add_page_break()
    add_heading(doc, "B.3 data.table vs. dplyr", 1)
    doc.add_paragraph(
        "We repeated Assignment 4 C3.1 by grouping daily returns by market and finding "
        "the mean return, standard deviation, and number of ticker-day observations."
    )
    add_table_caption(doc, "Code comparison. The same grouped summary in two syntaxes")
    add_code_comparison(
        doc,
        """market_stats_dplyr <-
  returns_by_market %>%
  group_by(Market) %>%
  summarise(
    mean_return =
      mean(Daily.Return),
    sd_return =
      sd(Daily.Return),
    observations = n(),
    .groups = "drop"
  ) %>%
  arrange(desc(mean_return))""",
        """market_stats_dt <-
  returns_dt[
    , .(
      mean_return =
        mean(Daily.Return),
      sd_return =
        sd(Daily.Return),
      observations = .N
    ),
    by = Market
  ][order(-mean_return)]""",
    )

    stats = read_csv_rows("b3_market_stats_dplyr.csv")
    stats_rows = [
        [
            row["Market"],
            f'{float(row["mean_return"]) * 100:.3f}%',
            f'{float(row["sd_return"]) * 100:.2f}%',
            f'{int(row["observations"]):,}',
        ]
        for row in stats
    ]
    add_table_caption(doc, "Table 5. Result from both dplyr and data.table")
    add_data_table(
        doc,
        ["Market", "Mean Return", "SD Return", "Observations"],
        stats_rows,
        [3000, 2100, 2100, 2160],
        [
            WD_ALIGN_PARAGRAPH.LEFT,
            WD_ALIGN_PARAGRAPH.CENTER,
            WD_ALIGN_PARAGRAPH.CENTER,
            WD_ALIGN_PARAGRAPH.RIGHT,
        ],
    )

    doc.add_paragraph(
        "Both versions give exactly the same result. We found dplyr easier to read "
        "because group_by() and summarise() show the steps in the order we think about "
        "them. The data.table version is shorter, and we would expect it to be faster "
        "and more memory-efficient on a much larger dataset. With 230,111 rows, both "
        "worked without a practical problem, so readability mattered more here."
    )


def add_b4(doc: Document) -> None:
    add_heading(doc, "B.4 Reflection", 1)
    doc.add_paragraph(
        "Yes. Reshaping the data let us draw several stock lines from one ggplot "
        "mapping, while grouping the Date column by month showed exactly when the major "
        "volatility spikes happened; the values were already in the dataset, but changing "
        "the shape and time grouping made the pattern visible."
    )

    disclosure = doc.add_paragraph()
    disclosure.paragraph_format.space_before = Pt(8)
    disclosure.paragraph_format.space_after = Pt(0)
    set_run_font(
        disclosure.add_run("We used ChatGPT for help with wording and formatting."),
        size=8,
        color=COLOR_MUTED,
        italic=True,
    )


def audit_document(doc: Document) -> None:
    section = doc.sections[0]
    assert section.page_width == PAGE_WIDTH
    assert section.page_height == PAGE_HEIGHT
    assert section.left_margin == PAGE_MARGIN
    assert section.right_margin == PAGE_MARGIN
    assert section.top_margin == PAGE_MARGIN
    assert section.bottom_margin == PAGE_MARGIN
    assert doc.styles["Normal"].font.name == FONT_BODY
    assert doc.styles["Normal"].font.size == Pt(11)
    assert doc.styles["Heading 1"].font.size == Pt(15)
    assert doc.styles["Heading 2"].font.size == Pt(12)
    assert all(
        sum(int(col.get(qn("w:w"))) for col in table._tbl.tblGrid.gridCol_lst)
        == CONTENT_WIDTH_DXA
        for table in doc.tables
    )


def build() -> Path:
    required_files = [
        FIGURE_DIR / "b1_reshape_indexed_prices.png",
        FIGURE_DIR / "b2_monthly_absolute_return.png",
        TABLE_DIR / "b1_wide.csv",
        TABLE_DIR / "b1_long.csv",
        TABLE_DIR / "b2_parsed_date_sample.csv",
        TABLE_DIR / "b2_top_volatility_months.csv",
        TABLE_DIR / "b3_market_stats_dplyr.csv",
    ]
    missing = [str(path) for path in required_files if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Run Rscript assignment_5/part_2/analysis.R before building the DOCX. Missing: "
            + ", ".join(missing)
        )

    doc = Document()
    configure_styles(doc)
    for section in doc.sections:
        configure_section(section)
        configure_header_footer(section)

    core = doc.core_properties
    core.title = "Assignment 5 Part 2 - Data Wrangling with R"
    core.subject = "Historical Stock Analysis"
    core.author = "Team 2"
    core.keywords = "R, tidyr, lubridate, data.table, dplyr, stock analysis"

    add_title_block(doc)
    add_b1(doc)
    add_b2(doc)
    add_b3(doc)
    add_b4(doc)
    audit_document(doc)
    doc.save(OUTPUT_PATH)
    return OUTPUT_PATH


if __name__ == "__main__":
    print(build())
